name: CI/CD Pipeline

# 只在PR和重要分支变更时运行，避免每次push都触发
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - '*.config.*'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
      continue-on-error: true  # 允许lint警告但不阻止构建
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Package Extension (Dry Run)
      run: |
        npm install -g @vscode/vsce
        vsce package --allow-missing-repository
      continue-on-error: true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: extension-package
        path: '*.vsix'
        retention-days: 7